services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  order:
      build:
        context: ./services/order
        dockerfile: DockerFile
      env_file: .env
      depends_on:
        - rabbitmq
      ports:
        - "8001:8000"

  insight-service:
    build: 
      context: ./services/insight_service
      dockerfile: DockerFile
    env_file: .env
    depends_on:
      - rabbitmq
    ports:
      - "8002:8000"

  market-ingestor:
    build: 
      context: ./services/market_ingestor
      dockerfile: DockerFile
    env_file: .env
    depends_on:
      - rabbitmq
    ports: 
      - "8003:8000"

